dist: trusty
language: csharp
cache:
  directories:
  - $HOME/.dotnet
solution: SharpCompress.sln
matrix:
  include:
    - dotnet: 2.0.0
      mono: none
      env: DOTNETCORE=1
script:
  - ./build.sh